# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacob Jiang的技术宅空间
email: kof2003@126.com
description: > # this means to ignore newlines until "baseurl:"
  蒋伟，男，85年出生于江苏泰兴，常混迹于南京，现居厦门。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: JiangweiJacob
github_username:  jacobjiangwei

# Build settings
markdown: kramdown
